export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL= 'BOOK_LIST_FAIL';

export const BOOK_DETAILS_REQUEST = 'BOOK_DETAILS_REQUEST';
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS';
export const BOOK_DETAILS_FAIL= 'BOOK_DETAILS_FAIL';


export const CART_CLEAR_ITEM='CART_CLEAR_ITEM';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_SET_QUANTITY='CART_SET_QUANTITY'

export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL';

export const USER_LOGOUT='USER_LOGOUT';
export const USER_LOGIN_REMOVE_ALERT='USER_LOGIN_REMOVE_ALERT';

export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL';
export const USER_REGISTER_REMOVE_ALERT='UUSER_REGISTER_REMOVE_ALERT';